sudo: required
services:
  - docker

before_install:
  - docker build -t grigatr/react-test -f ./client/dockerfile.dev ./client

script:
  - docker run -e CI=true grigatr/react-test npm test 

after_success:
  - docker build -t grigatr/multi-client ./client
  - docker build -t grigatr/multi-nginx ./nginx
  - docker build -t grigatr/multi-server ./server
  - docker build -t grigatr/multi-worker ./worker
  #Log in to the Dcoker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push then to docker hub
  - docker push grigatr/multi-nginx
  - docker push grigatr/multi-server
  - docker push grigatr/multi-worker
  - docker push grigatr/multi-client

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-central-1-268858658314
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY